FROM python:3.9-slim

WORKDIR /app

# Définir les variables d'environnement pour TensorFlow
ENV TF_CPP_MIN_LOG_LEVEL=3
ENV TF_ENABLE_ONEDNN_OPTS=0

# Copier les fichiers de dépendances
COPY backend/requirements.txt /app/

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code source
COPY backend/ /app/

# Créer un répertoire pour les données persistantes
RUN mkdir -p /app/data
VOLUME /app/data

# Exposer les ports
EXPOSE 5000 5001 5002

# Commande de démarrage
CMD ["python", "start_backend.py"]